name: Deploy Kontext automation runbooks for each
on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files:
          - datecheck
          - getadusers
          - processmanagement
          - updateuserattribute
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      - name: Get result
        run: echo ${{ matrix.files }}.py
      - name: Deploy Azure runbooks
        uses: azure/powershell@v1
        with:
          inlineScript: |
            pushd ./scripts/runbooks
            Import-AzAutomationRunbook -Path ${{ matrix.files }}.py  -Name ${{ matrix.files }} -Type Python3 -AutomationAccountName 'auto-wow-account' -ResourceGroupName 'NetworkWatcherRG' -Force
            Publish-AzAutomationRunbook -Name ${{ matrix.files }} -AutomationAccountName 'auto-wow-account'  -ResourceGroupName 'NetworkWatcherRG'
            popd
          azPSVersion: "latest"

      - name: logout
        run: |
          az logout
