name: "deploy GIT logic app"

on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        required: true

jobs:
  logic_app_build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Package logic
      run: (cd logic; mkdir -p ../output; zip -r ../output/logic.zip .)
    - name: Upload app zip package
      uses: actions/upload-artifact@v2
      with:
        name: logic
        path: ./output/
        retention-days: 1

  logic_app_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [logic_app_build]
    environment:
      name: Dev
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true
    - uses: actions/download-artifact@master
      with:
        name: logic
        path: ./output/
        
    - name: Get publish Profile
      id: publishprofile
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $profile = Get-AzWebAppPublishingProfile `
              -ResourceGroupName ${{inputs.resourceGroupName}} `
              -Name logic-app-three
          $profile = $profile.Replace("`r", "").Replace("`n", "")
          Write-Output "::set-output name=profile::$profile"
        azPSVersion: latest

    - name: Deploy to Azure Logic App
      uses: Azure/functions-action@v1.3.1
      id: la
      with:
        app-name: ${{secrets.RG_LA}}
        package: './output/logic.zip'
        publish-profile: ${{steps.publishprofile.outputs.profile}}

    - name: Swap parameter files
      id: params
      uses: azure/powershell@v1
      with:
        inlineScript: |
          az functionapp deploy --resource-group ${{inputs.resourceGroupName}} --name logic-app-three --src-path  logic/azure.parameters.json --type static --target-path parameters.json
        azPSVersion: latest