name: "deploy logic app template"

on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        required: true
jobs:
  deploy-template:
    runs-on: ubuntu-latest
    # needs: [logic_app_build]
    # environment:
    #   name: Dev
    # steps:
    # - name: Checkout
    #   uses: actions/checkout@v1
    # - name: Login via Az module
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{secrets.AZURE_CREDENTIALS}}
    #     enable-AzPSSession: true
    # - uses: actions/download-artifact@master
    #   with:
    #     name: logic
    #     path: ./output/
        
    # - name: Get publish Profile
    #   id: publishprofile
    #   uses: azure/powershell@v1
    #   with:
    #     inlineScript: |
    #       $profile = Get-AzWebAppPublishingProfile `
    #           -ResourceGroupName ${{ secrets.RG_LA }} `
    #           -Name ${{ env.LA_NAME }}
    #       $profile = $profile.Replace("`r", "").Replace("`n", "")
    #       Write-Output "::set-output name=profile::$profile"
    #     azPSVersion: latest

    # - name: Deploy to Azure Logic App
    #   uses: Azure/functions-action@v1.3.1
    #   id: la
    #   with:
    #     app-name: ${{secrets.RG_LA}}
    #     package: './output/logic.zip'
    #     publish-profile: ${{steps.publishprofile.outputs.profile}}

    # - name: Swap parameter files
    #   id: params
    #   uses: azure/powershell@v1
    #   with:
    #     inlineScript: |
    #       az functionapp deploy --resource-group ${{ secrets.RG_LA }} --name ${{ env.LA_NAME }} --src-path  logic/azure.parameters.json --type static --target-path parameters.json
    #     azPSVersion: latest




    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: run ls
        run: ls ./templates

      - name: deploy template
        id: deploy
        uses: azure/powershell@v1
        with:
          inlineScript: |
            az deployment group create -g ${{inputs.resourceGroupName}} --template-file ./templates/template.json
          # --parameters "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#"
          azPSVersion: latest

###############################################  2

# - task: AzureResourceManagerTemplateDeployment@3
#                   displayName: "Deploy ARM template"
#                   inputs:
#                     azureResourceManagerConnection: $(connectionName)
#                     subscriptionName: $(subscriptionId)
#                     resourceGroupName: $(resourceGroupName)
#                     location: $(location)
#                     csmFile: $(Pipeline.Workspace)/armtemplate/**/workflow.json
#                     csmParametersFile: $(Pipeline.Workspace)/armtemplate/**/parameters.json
#                     deploymentMode: "Incremental"
#                     overrideParameters: -subscriptionId $(subscriptionId) -resourceGroupName $(resourceGroupName) -location $(locationParameter)
###############################################  2

##########################################################  1
# steps:
# - task: AzureResourceManagerTemplateDeployment@3
#   displayName: 'ARM Template deployment: Resource Group scope'
#   inputs:
#     azureResourceManagerConnection: 'SubsName (XXXX)'
#     subscriptionId: 'XXXXXXXX'
#     resourceGroupName: 'XXXXXXX'
#     location: 'South Central US'
#     csmFile: '$(System.DefaultWorkingDirectory)/_EDW-AzureResources/EDWResources/ADFErrorPollingLogicApp-template.json'
# csmParametersFile: '$(System.DefaultWorkingDirectory)/_EDW-AzureResources/EDWResources/ADFErrorPollingLogicApp-parameters.json'
# overrideParameters: '-workflows_adffailure_logic_app_name "logic-ccok-XXXX" -workflows_teamspost_logic_app_name "logic-ccok-XXXX" -environment "dev" -app_name "EDW" -teamsName "EDW-XXXXX" -teamsChannelName "ADF-DEVXXXX" -dataFactoryName "adf-cXXXX"'
###########################################################  1