name: Python application

on:
  workflow_dispach:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10.13']
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.13
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Export environment
      run: |
        export CONTAINER=TEST
    - name: Install dependencies
      run: |
          pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest emails
        pytest subscriptions
 