
name: AzurePowerShellSample
on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
        
    - name: Run Azure PowerShell inline script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Get-AzAutomationAccount -ResourceGroupName "cloud-shell-storage-westeurope"
          $sub = Get-AzSubscription -ErrorAction SilentlyContinue
          if(-not($sub))
          {
              Connect-AzAccount
          }
          $resourceGroup = "NetworkWatcherRG"
          $automationAccount = "tryingCT"
          $storageAccount = "myfirsttrail"
          $key = Get-AzStorageAccountKey -ResourceGroupName $resourceGroup -Name $storageAccount

          $context = New-AzStorageContext -StorageAccountName $storageAccount -StorageAccountKey $key[0].value

          $fileShare = New-AzStorageShare -Name 'resource-templates' -Context $context

          Set-AzStorageFileContent -ShareName $fileShare.Name -Context $context -Source $storageTemplate
        azPSVersion: "latest"
          # $userAssignedManagedIdentity = "userAssignedManagedIdentity"
          # $storageTemplate = "path\storageTemplate.json"
          # $runbookScript = "path\runbookScript.ps1"